# Generated by Django 4.1.7 on 2023-04-13 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('houseno', models.CharField(max_length=25)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('tell', models.CharField(max_length=15)),
                ('martial_status', models.CharField(max_length=15)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('enviroment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.enviroment')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=7)),
                ('tell', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=7)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.service')),
            ],
        ),
        migrations.AddField(
            model_name='enviroment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.house'),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecmsapp.renter'),
        ),
    ]
