# Generated by Django 4.1.7 on 2023-05-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.CharField(default='Opened', max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='process',
            field=models.CharField(default='Un-Paid', max_length=15),
        ),
    ]
