# Generated by Django 4.1.7 on 2023-05-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0003_alter_service_month_alter_transaction_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='month',
        ),
        migrations.RemoveField(
            model_name='service',
            name='process',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='month',
        ),
    ]
