# Generated by Django 4.1.7 on 2023-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0004_remove_service_month_remove_service_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='process',
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.CharField(default='Un-Paid', max_length=15),
        ),
    ]
