# Generated by Django 4.1.7 on 2023-05-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0005_remove_transaction_process_service_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(max_length=10),
        ),
    ]
