# Generated by Django 4.2.1 on 2023-05-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0006_alter_transaction_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLoggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('logger_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
