# Generated by Django 4.2.1 on 2023-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0007_userloggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloggers',
            name='device',
            field=models.TextField(null=True),
        ),
    ]
