# Generated by Django 4.2.1 on 2023-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmsapp', '0008_userloggers_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('houseno', models.CharField(max_length=25)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
